config/routes.rb
Gasoline::Application.routes.draw do
  resources :cars

  get "home/index"

  root :to => 'home#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cars }
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/new
  # GET /cars/new.json
  def new
    @car = Car.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(params[:car])

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render json: @car, status: :created, location: @car }
      else
        format.html { render action: "new" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cars/1
  # PUT /cars/1.json
  def update
    @car = Car.find(params[:id])

    respond_to do |format|
      if @car.update_attributes(params[:car])
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :make %><br />
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :licenseplate %><br />
    <%= f.text_field :licenseplate %>
  </div>
  <div class="field">
    <%= f.label :vin %><br />
    <%= f.text_field :vin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<h1>Listing cars</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Make</th>
    <th>Model</th>
    <th>Year</th>
    <th>Licenseplate</th>
    <th>Vin</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cars.each do |car| %>
  <tr>
    <td><%= car.name %></td>
    <td><%= car.make %></td>
    <td><%= car.model %></td>
    <td><%= car.year %></td>
    <td><%= car.licenseplate %></td>
    <td><%= car.vin %></td>
    <td><%= link_to 'Show', car %></td>
    <td><%= link_to 'Edit', edit_car_path(car) %></td>
    <td><%= link_to 'Destroy', car, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @car.name %>
</p>

<p>
  <b>Make:</b>
  <%= @car.make %>
</p>

<p>
  <b>Model:</b>
  <%= @car.model %>
</p>

<p>
  <b>Year:</b>
  <%= @car.year %>
</p>

<p>
  <b>Licenseplate:</b>
  <%= @car.licenseplate %>
</p>

<p>
  <b>Vin:</b>
  <%= @car.vin %>
</p>


<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/home/index.html.erb
<!-- Boilerplate from http://www.engineyard.com/blog/2012/building-mobile-web-applications-with-kendo-ui-and-engine-yard -->
<div data-role="layout" data-id="app">
   <header data-role="header">
      <div data-role="navbar">Gasoline</div>
   </header>
   <footer data-role="footer">
      <div data-role="tabstrip">
         <a href="#mycars" data-icon="info">Cars</a>
         <a href="#info" data-icon="recents">Info</a>
      </div>
   </footer>
</div>
 
<div data-role="view" data-init="getCars" data-layout="app" data-title="mycars" id="mycars">
   <ul id="cars"></ul>
</div>
 
<div data-role="view" data-layout="app" data-init="getSessions" data-title="info" id="info">
   <div id="infos"></div>
</div>

<script type="text/x-kendo-template" id="carsTemplate">
	<div class="left">
		<div class='make'>${ make }</div>
		<div class='model'>${ model }</div>
	</div>
	<div>${ name }</div>
</script>

<script>
  var app = new kendo.mobile.Application($(document).body);

  var getCars = function() {
	  $("#cars").kendoMobileListView({
		  dataSource: kendo.data.DataSource.create({
			  transport: {
				  read: "cars.json"
			  },
			  sort: { field: "name", dir: "asc" }
		  }),
		  template: $("#carsTemplate").html()
	  });
  }

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gasoline</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>